apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarkus-demo
  template:
    metadata:
      labels:
        app: devops-demo
        env: dev
    spec:
      containers:
      - name: devops-demo
        image: quay.io/rhdevelopers/quarkus-demo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
#kubectl get pods --show-labels
#kubectl exec -it devops-demo-deployment-5979886fb7-c888m -- curl localhost:8080
