#First run the "webserver.Dockerfile"  and make the image available locally.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "devopsworkshop-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "devopsworkshop"
  template:
    metadata:
      labels:
        app: "devopsworkshop"
    spec:
      containers:
        - image: nginx
          name: webserver1
          ports:
            - containerPort: 80
# kubectl port-forward pods/mongo-75f59d57f4-4nd6q 806:80