apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: rs-devops-demo
spec:
    replicas: 3
    selector:
       matchLabels:
          app: devops-demo
    template:
       metadata:
          labels:
             app: devops-demo
             env: dev
       spec:
          containers:
          - name: devops-demo
            image: quay.io/rhdevelopers/quarkus-demo:v1
            
     #watch kubectl get pods --show-labels
     #kubectl get rs
     #kubectl describe rs rs-devops-demo
     #kubectl delete pod rs-devops-demo-<<id>>
