apiVersion: v1
kind: Service
metadata:
  name: the-service
spec:
  selector:
    app: devops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  
  #watch kubectl get services
  #On Minikube without an Ingress controller, <pending> will not become a real external IP. Optional: Setup Minikube Ingress
  #https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
  #IP=$(minikube ip -p devnation)
  #PORT=$(kubectl get service/the-service -o jsonpath="{.spec.ports[*].nodePort}")
  #curl $IP:$PORT
